### ISSUE TITLE
build_all.sh is not working (not able to generate article.pdf)

### ISSUE THREAD

**Issue by wi25hoy** [ReScience/MLRC#93]
I have completed all  my files editing but i am struggling with this issue. what might be the possible issue? metadata.tex is not foung or generated.

$ ./build_all.sh
Building ahmed2022re/
/c/Users/Waqas Ahmed/MLRC_2/MLRC/2021/ahmed2022re/journal
Reverting Windows console CPs to (in,out) = (65001,65001)
Win CP console initial and current in/out Win: (65001, 65001), (1252, 1252)
Coding system for system and terminal: 'CP1252'
---
Rc files read:
  NONE
Latexmk: This is Latexmk, John Collins, 17 Mar. 2022. Version 4.77, version: 4.77.
No specific requests made, so using default for latexmk.
Latexmk: Doing main (small) clean up for 'article.tex'
Latexmk: Doing extra clean up (of final output files) for 'article.tex'
Latexmk: Doing main (small) clean up for 'content.tex'
Latexmk: Doing extra clean up (of final output files) for 'content.tex'
Latexmk: Doing main (small) clean up for 'header.tex'
Latexmk: Doing extra clean up (of final output files) for 'header.tex'
rm: cannot remove 'metadata.tex': No such file or directory
C:\Users\Waqas Ahmed\AppData\Local\Microsoft\WindowsApps\python3.exe: can't open file 'C:\Users\Waqas': [Errno 2] No such file or directory
make: *** [Makefile:18: metadata.tex] Error 2
Build complete
rm: cannot remove 'article.aux': No such file or directory
rm: cannot remove 'article.bbl': No such file or directory
rm: cannot remove 'article.blg': No such file or directory
rm: cannot remove 'article.fdb_latexmk': No such file or directory
rm: cannot remove 'article.fls': No such file or directory
rm: cannot remove 'article.out': No such file or directory
rm: cannot remove 'article.log': No such file or directory
rm: cannot remove 'article.run.xml': No such file or directory
rm: cannot remove 'article.bcf': No such file or directory
Building editorial/
/c/Users/Waqas Ahmed/MLRC_2/MLRC/2021/editorial/journal
Makefile:1: *** missing separator.  Stop.
rm: cannot remove 'metadata.tex': No such file or directory
Makefile:1: *** missing separator.  Stop.
Build complete
rm: cannot remove 'article.aux': No such file or directory
rm: cannot remove 'article.bbl': No such file or directory
rm: cannot remove 'article.blg': No such file or directory
rm: cannot remove 'article.fdb_latexmk': No such file or directory
rm: cannot remove 'article.fls': No such file or directory
rm: cannot remove 'article.out': No such file or directory
rm: cannot remove 'article.log': No such file or directory
rm: cannot remove 'article.run.xml': No such file or directory
rm: cannot remove 'article.bcf': No such file or directory

**Comment by ShuaiWang97** [comment]
We have the same issue too.

**Comment by wi25hoy** [comment]
seems like its a common problem as i have seen in previous issues as well.  hopefully, ACs could help us out.

**Comment by jeroenwijnen98** [comment]
I have a similar issue, only with me the problems appear to start because the file article.bbl cannot be found:

`Rc files read:
  NONE
Latexmk: This is Latexmk, John Collins, 17 Mar. 2022. Version 4.77, version: 4.77.
No specific requests made, so using default for latexmk.
Latexmk: Doing main (small) clean up for 'article.tex'
Latexmk: Doing extra clean up (of final output files) for 'article.tex'
Latexmk: Doing main (small) clean up for 'content.tex'
Latexmk: Doing extra clean up (of final output files) for 'content.tex'
Latexmk: Doing main (small) clean up for 'header.tex'
Latexmk: Doing extra clean up (of final output files) for 'header.tex'
Latexmk: Doing main (small) clean up for 'metadata.tex'
Latexmk: Doing extra clean up (of final output files) for 'metadata.tex'
Latexmk: Missing bbl file 'article.bbl' in following:
 No file article.bbl.
make[1]: *** No rule to make target `article.bbl'.  Stop.
Build complete
Building petcu2022replication/
/Users/marcwijnen/Documents/GitHub/MLRC/2021/petcu2022replication/journal
Rc files read:
  NONE
Latexmk: This is Latexmk, John Collins, 17 Mar. 2022. Version 4.77, version: 4.77.
No specific requests made, so using default for latexmk.
Latexmk: Doing main (small) clean up for 'article.tex'
Latexmk: Doing extra clean up (of final output files) for 'article.tex'
Latexmk: Doing main (small) clean up for 'content.tex'
Latexmk: Doing extra clean up (of final output files) for 'content.tex'
Latexmk: Doing main (small) clean up for 'header.tex'
Latexmk: Doing extra clean up (of final output files) for 'header.tex'
rm: metadata.tex: No such file or directory
Traceback (most recent call last):
  File "/Users/marcwijnen/Documents/GitHub/MLRC/2021/petcu2022replication/journal/./yaml-to-latex.py", line 93, in <module>
    content = generate_latex_metadata(filename_in, article)
  File "/Users/marcwijnen/Documents/GitHub/MLRC/2021/petcu2022replication/journal/./yaml-to-latex.py", line 10, in generate_latex_metadata
    "% DO NOT EDIT - automatically generated from {filename}\n\n"
AttributeError: 'str' object has no attribute 'name'
make: *** [metadata.tex] Error 1
Build complete
rm: article.aux: No such file or directory
rm: article.bbl: No such file or directory
rm: article.blg: No such file or directory
rm: article.fdb_latexmk: No such file or directory
rm: article.fls: No such file or directory
rm: article.out: No such file or directory
rm: article.log: No such file or directory
rm: article.run.xml: No such file or directory
rm: article.bcf: No such file or directory
(code) re-stud-146-50-222-219:2021 marcwijnen$ ./build_all.sh
Building editorial/
/Users/marcwijnen/Documents/GitHub/MLRC/2021/editorial/journal
Rc files read:
  NONE
Latexmk: This is Latexmk, John Collins, 17 Mar. 2022. Version 4.77, version: 4.77.
No specific requests made, so using default for latexmk.
Latexmk: Doing main (small) clean up for 'article.tex'
Latexmk: Doing extra clean up (of final output files) for 'article.tex'
Latexmk: Doing main (small) clean up for 'content.tex'
Latexmk: Doing extra clean up (of final output files) for 'content.tex'
Latexmk: Doing main (small) clean up for 'header.tex'
Latexmk: Doing extra clean up (of final output files) for 'header.tex'
Latexmk: Doing main (small) clean up for 'metadata.tex'
Latexmk: Doing extra clean up (of final output files) for 'metadata.tex'
Latexmk: Missing bbl file 'article.bbl' in following:
 No file article.bbl.
make[1]: *** No rule to make target `article.bbl'.  Stop.
Build complete
Building petcu2022replication/
/Users/marcwijnen/Documents/GitHub/MLRC/2021/petcu2022replication/journal
Rc files read:
  NONE
Latexmk: This is Latexmk, John Collins, 17 Mar. 2022. Version 4.77, version: 4.77.
No specific requests made, so using default for latexmk.
Latexmk: Doing main (small) clean up for 'article.tex'
Latexmk: Doing extra clean up (of final output files) for 'article.tex'
Latexmk: Doing main (small) clean up for 'content.tex'
Latexmk: Doing extra clean up (of final output files) for 'content.tex'
Latexmk: Doing main (small) clean up for 'header.tex'
Latexmk: Doing extra clean up (of final output files) for 'header.tex'
rm: metadata.tex: No such file or directory
Traceback (most recent call last):
  File "/Users/marcwijnen/Documents/GitHub/MLRC/2021/petcu2022replication/journal/./yaml-to-latex.py", line 93, in <module>
    content = generate_latex_metadata(filename_in, article)
  File "/Users/marcwijnen/Documents/GitHub/MLRC/2021/petcu2022replication/journal/./yaml-to-latex.py", line 10, in generate_latex_metadata
    "% DO NOT EDIT - automatically generated from {filename}\n\n"
AttributeError: 'str' object has no attribute 'name'
make: *** [metadata.tex] Error 1
Build complete
rm: article.aux: No such file or directory
rm: article.bbl: No such file or directory
rm: article.blg: No such file or directory
rm: article.fdb_latexmk: No such file or directory
rm: article.fls: No such file or directory
rm: article.out: No such file or directory
rm: article.log: No such file or directory
rm: article.run.xml: No such file or directory
rm: article.bcf: No such file or directory`

**Comment by GuillyK** [comment]
I have the same error as @jeroenwijnen98 where it builds. but has an error on 'name'

`Rc files read:
  NONE
Latexmk: This is Latexmk, John Collins, 17 Mar. 2022. Version 4.77, version: 4.77.
No specific requests made, so using default for latexmk.
Latexmk: Doing main (small) clean up for 'article.tex'
Latexmk: Doing extra clean up (of final output files) for 'article.tex'
Latexmk: Doing main (small) clean up for 'content.tex'
Latexmk: Doing extra clean up (of final output files) for 'content.tex'
Latexmk: Doing main (small) clean up for 'header.tex'
Latexmk: Doing extra clean up (of final output files) for 'header.tex'
rm: metadata.tex: No such file or directory
Traceback (most recent call last):
  File "./yaml-to-latex.py", line 93, in <module>
    content = generate_latex_metadata(filename_in, article)
  File "./yaml-to-latex.py", line 10, in generate_latex_metadata
    "% DO NOT EDIT - automatically generated from {filename}\n\n"
AttributeError: 'str' object has no attribute 'name'
make: *** [metadata.tex] Error 1
Build complete
rm: article.aux: No such file or directory
rm: article.bbl: No such file or directory
rm: article.blg: No such file or directory
rm: article.fdb_latexmk: No such file or directory
rm: article.fls: No such file or directory
rm: article.out: No such file or directory
rm: article.log: No such file or directory
rm: article.run.xml: No such file or directory
rm: article.bcf: No such file or directory

**Comment by koustuvsinha** [comment]
Hi, please flag these issues in your own PR's, we will respond within them individually. Thanks!

**Comment by ShuaiWang97** [comment]
We got advice from our colleague, for Ubuntu: sudo apt-get install texlive-bibtex-extra biber

**Comment by koustuvsinha** [comment]
Closing this as most of you have resolved it. Feel free to re-open if you are facing the same issue.
